### ISSUE TITLE
Add icon path attribute

### ISSUE THREAD

**Issue by rugk** [AliasIO/Wappalyzer#1004]
Based on the problem of #1002 where `/` is in the name of the feature the icon path did not match. An implementation of an escaping feature could possibly solve this, but IMHO it's better to add another JSON attribute for an alternative file path/file name.

This would not only solve this issue, but it would also help to reduce the amount of icons you have to upload. [E.g.](https://github.com/AliasIO/Wappalyzer/blob/master/src/icons/HP%20ChaiServer.png) [of](https://github.com/AliasIO/Wappalyzer/blob/master/src/icons/HP%20Compact%20Server.png) [HP](https://github.com/AliasIO/Wappalyzer/blob/master/src/icons/HP%20ProCurve.png) [are](https://github.com/AliasIO/Wappalyzer/blob/master/src/icons/HP%20System%20Management.png) [already](https://github.com/AliasIO/Wappalyzer/blob/master/src/icons/HP%20iLO.png) [6 pictures](https://github.com/AliasIO/Wappalyzer/blob/master/src/icons/HP.png) uploaded.
Using one picture for them all would also allow easier updating if the logo of HP changes.

Of course there should be a fallback to the current method if the file name attribute is not present in the json of an app.

CC: @DaAwesomeP

**Comment by AliasIO** [comment]
It would solve other issues as well, such as using different file types (SVG and PNG). I'd have to make some changes to the website if we go ahead with this but it's probably worth doing.

**Comment by DaAwesomeP** [comment]
I can work on changing the icon testing and compression to be compatible. I can make it look for the icon based on the application's name or use the icon path attribute if it's present. I think that it should be option and only used for special cases to prevent the need to add the new attribute to all of the current apps.

However, be mindful of SVG file sizes. SVGs ***may*** be significantly larger, even with lots of compression. The size of a PNG vs. the size of an SVG depends entirely on how the SVG was created. Depending on who created it with what tool, it can either be more efficient than the PNG counterpart or drastically worse. Since the SVGs will be physically small on screen (not necessarily pixels coughretinacough, but to the eye), I can have the compressor round off the decimals/lower the precision. **'ll try to make it pull an error if any images are embedded in the SVG, as this defeats the purpose of the SVG and makes it very large in file size,* but I don't know if I'll be able to.

We could also use Gzipped SVGs, but I don't know how that will impact performance. Also, take a look at [this post](http://cloudinary.com/blog/google_s_new_logo_might_not_be_as_small_as_claimed) about a few different files types and sizes (based on Google's new logo, but informative).

**Comment by DaAwesomeP** [comment]
If no `icon` attribute is present, I will make it first look for an SVG and then a PNG. If none or both are present, it will pull an error.

**Comment by AliasIO** [comment]
Let's just an an 'icon' field that specifies the filename including extension. To start we can mass update the JSON to include `icon: '<application_name>.png'`. The tests will need to use that field as well.

**Comment by DaAwesomeP** [comment]
@AliasIO, you want to have an `icon` attribute for every app? For the apps that don't need it it could save space by not being a required field. I'll make it required in the tests for now.

**Comment by AliasIO** [comment]
Yes, let's make it a required field.

**Comment by DaAwesomeP** [comment]
I did not remove any of the duplicate icons in pull #1012 (i.e. the HP example provided by @rugk above), but it should be possible to fix that after it is merged. The HTTP2 vs. HTTP/2 issue could also be resolved.

**Comment by rugk** [comment]
As #1012 was merged I'll close this.

**Comment by DaAwesomeP** [comment]
@rugk I think that it should remain open until SVG support is added to the drivers and you can add a separate filename for HTTP/2.

**Comment by rugk** [comment]
Actually you can add a separate filename. I mean that's the purpose of https://github.com/AliasIO/Wappalyzer/pull/1012.
SVG support is not covered by this issue. You may create a new one to track this.
