### ISSUE TITLE
Add an option to ignore specific websites

### ISSUE THREAD

**Issue by Qrysto** [AliasIO/Wappalyzer#1044]
I'm a web developer and for some reasons I don't know, Wappalyzer always crashes on my localhost testing site. Can we have an option for Wappalyzer to ignore some specific sites?

FYI, it crashes on line 55 of Wappalyzer/js/iframe.js, and I'm developing a React website, not sure if it relates

**Comment by AliasIO** [comment]
Are you able to provide more information on what happens when it crashes? I.e. a traceback or any error message?

**Comment by rayshan** [comment]
+1 this is nice have in general

**Comment by Qrysto** [comment]
@AliasIO here the stack trace is

<img width="581" alt="screen shot 2016-01-06 at 17 01 27" src="https://cloud.githubusercontent.com/assets/8004784/12140046/4be3ac3c-b497-11e5-9d9b-f4165f9b4b61.png">

**Comment by q--** [comment]
The offending file (not included in the Wappalyzer source on GitHub, so I pasted it in a Gist) is [iframe.js](https://gist.github.com/q--/225cf755d9ac29d600c0).

After downloading the Chrome extension, I also noticed Wappalyzer is violating the GPL by not including a copy of the license with the extension nor mentioning all of its contents are GPL licensed. (Only the file wappalyzer.js includes a mention of the license, which is not enough for the GPL.) When `grep`-ing around, I noticed it is also violating the BSD license because the file widgets.css is licensed under the BSD-license but the license has not been included, even though the license clearly says so.

(Actually, unless I'm mistaken Wappalyzer strictly hasn't been in compliance with the GPL for much longer because it doesn't list all copyright holders (which is everyone who has ever contributed code that is still part of Wappalyzer or upon which current parts of Wappalyzer have been based) in the source code. I didn't bring this up earlier because attribution in the code itself isn't really important to me, at least in this case.)

You might want to fix these things. (Disclaimer: IANAL and it's been a while since I checked the GPL, this comment is not legal advice.)

Also, you could use https://developer.mozilla.org/docs/Web/API/URL instead of creating an anchor element in your code.

**Comment by AliasIO** [comment]
We can include the license in the build but I think it's enough to simply declare the license, like in the Firefox manifest file. The Chrome version is missing this though. GPL doesn't require all bundled code to have the same license. I don't believe the GPL requires contributors to be listed either but they can be found [here](https://github.com/AliasIO/Wappalyzer/network/members).

You're right about the BSD license, a LICENSE file should be included in that directory.

**Comment by AliasIO** [comment]
Rather than an option to ignore certain sites I much prefer fixing the issues. I just published a version that should address the iframe.js bug.
