### ISSUE TITLE
Penguin.png appears as an unstaged change

### ISSUE THREAD

**Issue by rugk** [AliasIO/Wappalyzer#1049]
As I experienced in https://github.com/AliasIO/Wappalyzer/pull/1002 the `Penguin.png` always appears as an uncommitted change even though I did not changed anything.

Is there anything special about this file?

**Comment by DaAwesomeP** [comment]
I have this problem too. I usually just ignore it. It might have to do with its version ID.

**Comment by q--** [comment]
It's because quite some time ago, somebody renamed _penguin.png_ to _Penguin.png_, did a `git add` for `Penguin.png` but neglected to do a `git rm` for _penguin.png_. As the result of this, git is now tracking both _penguin.png_ and _Penguin.png_. This is causing problems on case-insensitive file systems, such as those used by Windows. (Also, the person who did this should have used `git mv` instead.)

See https://github.com/AliasIO/Wappalyzer/pull/1002#issuecomment-169600047.

**Comment by ioli** [comment]
Hello Please add my App

anchorCache® Caching Class

[ The anchorCache® hehigh-performance object caching system ever. ]

http://anchorcache.eu/

**Comment by rugk** [comment]
@ioli Please do not hijack issues.
As it seems you already do it by yourself: https://github.com/AliasIO/Wappalyzer/pull/1051

---

> I fixed this for AliasIO/Wappalyzer.

Okay, so I'm closing this issue as it's fixed in the upstream repo here. In case others have this issue they can also "solve" it with a brute way by just deleting the fork and all files of their fork (also delete the fork on GitHub) and reforking this repo. Of course you should not have any open PRs or you have to recreate them.
This is how I finally did this.
