### ISSUE TITLE
Add Image Help

### ISSUE THREAD

**Issue by ioli** [AliasIO/Wappalyzer#1067]
how to add my pc to github icon ? variable ?

drag and drop not working , where is parameter add image to github ?

example steps:

1. convert image : https://iconverticons.com/icons/1e3d6a26badde7ea/
2. save images PC
3.  drag and drop images pc to github do not working !!

where to use papameter add image to github ?

example:   icon/test.png

Thank you!

**Comment by DaAwesomeP** [comment]
@ioli You need to use the `git` command from the terminal (OSX), command prompt (Windows), or shell/bash prompt (Linux). Normally, I would recomend this, but you seem pretty new to all of this, so you might want to start with [GitHub Desktop](https://desktop.github.com/). That way you don't have to mess with SSH keys or the MSYS2 Bash on Windows.

1. Install GitHub Desktop form here: https://desktop.github.com/
2. Fork Wappalyzer by going to the repo home (https://github.com/AliasIO/Wappalyzer) and clicking the Fork button in the top right. This will in a way copy the repo to your account. This you can (through GitHub Desktop) clone to your computer. You will have a folder that you can make changes in.
3. After you make some changes, you can create a commit with a message describing your changes and then push (upload) it to your fork (the "copy" repo that you made).
4. Back on the GitHub website, so to your fork and click the green button that says "New Pull Request." From there I think that you'll figure it out.

This isn't in any instructions anywhere in this repo because these instructions aren't specific to this project. All Git projects work in this way.

**Comment by ioli** [comment]
ok thank you!

**Comment by DaAwesomeP** [comment]
@ioli Glad to help! Please close this issue when you get a chance.
