### ISSUE TITLE
Pale Moon compatibility ?

### ISSUE THREAD

**Issue by patheticcockroach** [AliasIO/Wappalyzer#1096]
Hi,

When I attempt to install the Firefox extension in Pale Moon, it says it's not compatible. However the bookmarklet method works fine, so I assume the extension is compatible and the version number of Pale Moon (latest version is 26.x) might be the only issue. Could you maybe make an xpi that will accept to install in Pale Moon ?

Thank

**Comment by toastal** [comment]
Hate to burst your bubble dude, but being on a version of Firefox almost 20 versions behind is a real security and web compatibility issue. I'd highly recommend moving to a vanilla version of Firefox over an outdated fork.

**Comment by patheticcockroach** [comment]
Well I mostly use it to test websites for compatibility with older/"indie" rendering engines, so that kind of the point ;) As for security I assumed that since they still update it regularly that was being dealt with...

**Comment by toastal** [comment]
PaleMoon doesn't have an independent rendering engine--it uses Gecko just like Firefox. The only difference is that PaleMoon doesn't have a competent team of people keeping up with security or the latest web technologies. As more and more people start using ECMAScript2015 anything outdated simply won't work. If you're looking to test "indie" rendering engines, you should try testing sites with things more along the lines of Dillo and Netsurf--there you'll see a different engines on projects that are still relatively keeping up to date on security.

**Comment by patheticcockroach** [comment]
Thanks for the details. Well I guess I'll close the issue then.

**Comment by al3xxx** [comment]
And yet, Pale Moon passes acid3 test with 100 score, while latest and greatest Firefox can get only to 99.
Speaking of competent teams and latest and greatest web technologies - at least Pale Moon guys managed not to break whatever compatibility there was before they started tinkering with that engine

**Comment by nonamethanks** [comment]
I stumbled upon this by searching on google. and I found a working solution for palemoon users if anyone's wondering. I'll leave it here for any other google searchers as I'm sure it'll help them.
Just download version  2.7.8.1-signed from https://addons.mozilla.org/en-us/firefox/addon/wappalyzer/versions/ and then replace the apps.json file inside the folder "<palemoon profile folder>/extensions/wappalyzer@crunchlabz.com/content" with the one under the "src" folder inside this repository. Everything'll work fine once you do.

And by the way @toastal ever considered applying for a disability check? Because you're a real mouthbreathing retard if I ever saw one.
