### ISSUE TITLE
JQuery & Wordpress version numbers not shown

### ISSUE THREAD

**Issue by FatKiwi** [AliasIO/Wappalyzer#1120]
JQuery version can be found easily in the filename, or the header inside the file.
Wordpress is understandable if you don't want to show full info, because of privacy concerns.

But it will be great if both show the versions.
I keep another extension just for this little minor issue. Hopefully you will fix it.

**Comment by q--** [comment]
Wappalyzer can detect both Woordpress' and jQuery's versions, but due to
design choices (such as not requesting external files like Wordpress'
readme.html) and technical limitations it won't detect them in all cases.

Also, specific examples where detection fails would be helpful. And
Wappalyzer currently doesn't (and possibly even can't) scan JavaScript file
sources.

2016-03-19 21:09 GMT+01:00 FatKiwi <notifications@github.com>:

**Comment by FatKiwi** [comment]
Hi, thanks for the response. You're right about some people hiding the versions.

I don't know if you detect query strings, but most of the cases they're helpful.

Here is example without version in URL or query string:
http://whoisleon.com/

JQuery 1.11.3 is detected by Appspector (outdated extension for Chrome). It somehow looks in the header of the js file.

Do you think it's possible to implement something like this? Maybe unpack the extension and look at the code?
