### ISSUE TITLE
Add preference to *not* change the icon

### ISSUE THREAD

**Issue by cfjedimaster** [AliasIO/Wappalyzer#1166]
Maybe I'm the only one, but it bugs me that as I browse, the icon changes based on tech used on the site. I'd really rather just have one 'core' Wappalyzer icon in the UI. I'm finding myself being momentarily confused when I see a new icon there and wondering what extension that is - then I remember it's Wappalyzer changing on the fly.

**Comment by AliasIO** [comment]
I'm not against this. Would you like to implement the option?

**Comment by uncleoptimus** [comment]
*You are not alone*.

I just went to the wapplyzer site, then here because I was wondering if there was a way to configure this. It used to be click on the orange blob and boom, sweet goodness.

I'd take the confusion factor you expressed a step further; plenty of times I glance at the extensions bar and have to poke around *and think for a bit* to figure out which one is wapplyzer. Naturally this leads to exhaustion of limited mental energies and I find I am unable to concentrate on work. So no work leads to no job, no job leads to the girlfriend leaves me. Next thing you know, I am alone for the rest of my life.

Other than that, I have to say I really love wapplyzer; Big Thanks to the folks who hath birthed and maintain it.

I just wish it were more immediately obvious (to me) at a glance which of the lil' buttons to click.

**Comment by AliasIO** [comment]
Just Chrome would be great!

**Comment by cfjedimaster** [comment]
So an FYI, and I know this is now OT, I'm not having luck getting this code into an environment where I can test. Got a copy of the repo and tried to load the extension unpacked (src/drivers/chrome),and Chrome wouldn't load it. Tried following the directions in the README and using Vagrant, but it prompts for a password and the readme doesn't say what should be used there. Any suggestions?

**Comment by Georgiel** [comment]
And another option, to have it static but with a counter kind of like this example 

![](http://www.technobuzz.net/wp-content/uploads/2011/07/notification.png)

**Comment by Georgiel** [comment]
sorry about the duplicate there, I couldn't seem to find the original and so thought it had been accidentally removed.

https://cloud.githubusercontent.com/assets/5931248/17548780/55b626ec-5ee5-11e6-807a-5e8daa1f8e5f.png

**Comment by GeorgeWL** [comment]
@aliasIO why is this closed now? 

The issue doesn't seem to be resolved yet.

**Comment by AliasIO** [comment]
It's resolved, see @DaAwesomeP's pull request.

**Comment by GeorgeWL** [comment]
But it's not pushed to the extension yet? @AliasIO

**Comment by DaAwesomeP** [comment]
@GeorgeWL Correct, the latest version (v4.0.1) was released prior to that pull. You may build the latest `master` or wait for the next release.
