### ISSUE TITLE
Wordpress not showing after last update.

### ISSUE THREAD

**Issue by xstatic** [AliasIO/Wappalyzer#1168]
Wordpress (and possibly others) is not showing the proper icon - just seeing the Wappalyzer icon.

**Comment by timneutkens** [comment]
Hi, not sure why this happens, but I think you mean that the wordpress.svg icon is not shown when it's the default icon you see in the chrome title bar.
Can you verify that this is the issue?
<img width="232" alt="screen shot 2016-06-13 at 22 35 56" src="https://cloud.githubusercontent.com/assets/6324199/16022261/3f1d288c-31b7-11e6-8a90-287566b3d0dc.png">

**Comment by xstatic** [comment]
Yes, confirmed, that is the issue.  Prior to the recent update Wordpress always showed its icon but now, it is showing the Wappalyzer icon.

**Comment by timneutkens** [comment]
Think it might have something to do with the icon being a svg.
@AliasIO might have some insights into this.

**Comment by AliasIO** [comment]
You're right @timneutkens, it's because the icon is SVG. I'm seeing this error in the console:

`Unchecked runtime.lastError while running pageAction.setIcon: Icon invalid.`

I also found this ancient bug report from 2009, which seems to be related and unresolved:

https://bugs.chromium.org/p/chromium/issues/detail?id=29683

We may need to export PNGs as part of the build. I can't believe [`pageAction.setIcon`](https://developer.chrome.com/extensions/pageAction#method-setIcon) doesn't support SVGs.

**Comment by timneutkens** [comment]
Hmm that is weird indeed, might use this package to convert: https://github.com/domenic/svg2png

**Comment by stefanos82** [comment]
@AliasIO I have the same behavior and not only that, at some cases it does not show any icon at all unless I press at the wappalyzer area.

![issue_as_of_2016-07-25_01-01-31](https://cloud.githubusercontent.com/assets/1777466/17086829/a4e72fe2-5204-11e6-815d-9642ccd27b1f.png)

**Comment by AliasIO** [comment]
Fixed in f82083b3402bc8fdcb4fc5c50a29a88e376f1de2, thanks all.
