### ISSUE TITLE
Wrong Position in multi monitor display

### ISSUE THREAD

**Issue by salarcode** [AliasIO/Wappalyzer#1276]
Hi, thanks for your work.
A bothering issues: In multi monitor system, the popup always display in the right hand monitor.

**Comment by gadcam** [comment]
The problem was reported a lot of times..
It is not a bug of Wappalyzer, I am not even sure it is a bug of the browser: I got the same strange behavior with GIMP for example.
This bug report seems to describe the same problem : https://bugzilla.mozilla.org/show_bug.cgi?id=61000
https://bugzilla.mozilla.org/show_bug.cgi?id=324949 is a bit similar
