### ISSUE TITLE
Broken screenshots in the Wiki

### ISSUE THREAD

**Issue by craiglondon** [AliasIO/Wappalyzer#1488]
https://github.com/AliasIO/Wappalyzer/wiki/Screenshots

**Comment by ppshobi** [comment]
Hey,  I have fixed the issue, since this is in the wiki, I couldn't directly make a pull request( I couldn't find any way :( ), please refer the URL
[https://github.com/ppshobi/WappalyzerWiki]

This is my first contribution to an open source project other than my own. please let me know what should I do...

**Comment by AliasIO** [comment]
Documentation has been moved to https://wappalyzer.com/docs.
