### ISSUE TITLE
Redux support

### ISSUE THREAD

**Issue by wesharehoodies** [AliasIO/Wappalyzer#1573]
Are there any plans for supporting Redux?

**Comment by jvoisin** [comment]
Feel free to issue a pull-request, it's not [that hard]( https://github.com/AliasIO/Wappalyzer/wiki/Contributing ).

If you're too lazy or unable to submit one, please provide at least some information about *Redux*, like a few websites where it's used (to help people to check if the detection is working), its official website, …

**Comment by wesharehoodies** [comment]
"It's not that hard" while you have literally almost  zero code documentation + the setup looks like a total waste of time?

No thanks.

**Comment by jvoisin** [comment]
The documentation says:

> Edit src/apps.json.
> Add a square icon in SVG format (preferred), or a 32x32 or larger PNG file to src/icons.

If you had open the [src/apps.json](https://github.com/AliasIO/Wappalyzer/blob/master/src/apps.json) file, you would have seen things like this:

```json
		"1C-Bitrix": {
			"cats": [
				"1"
			],
			"headers": {
				"Set-Cookie": "BITRIX_",
				"X-Powered-CMS": "Bitrix Site Manager"
			},
			"html": "(?:<link[^>]+components/bitrix|(?:src|href)=\"/bitrix/(?:js|templates))",
			"icon": "1C-Bitrix.png",
			"implies": "PHP",
			"script": "1c-bitrix",
			"website": "http://www.1c-bitrix.ru"
		},
```

It shouldn't be hard to infer the majority of the fields. Some might be a bit non-obvious, but fortunately, [the documentation]( https://github.com/AliasIO/Wappalyzer/wiki/Specification ) has a great list of explanations about every single field.

You can of course test your pull-request, but since you're only adding an application, this shouldn't be necessary.

Again, if you're too lazy of unable to issue a pull-request for *Redux*, please provide at least some information about Redux, like a few websites where it's used (to help people to check if the detection is working), its official website, …

**Comment by wesharehoodies** [comment]
![redux logo](https://cloud.githubusercontent.com/assets/11220736/26193586/6aa56df4-3bbe-11e7-843f-57913dc453ca.png)

### Redux is a predictable state container for JavaScript apps.

Official website: http://redux.js.org/#

### Sites that use redux 100%

https://open.spotify.com/browse

https://soundcloud-redux.herokuapp.com/

**Comment by jvoisin** [comment]
I failed to see a possible way to detect Redux on those websites :/
It's not included with a recognisable filename, nor does it provide a `redux` object or anything similar :/

**Comment by wesharehoodies** [comment]
@jvoisin Every Redux has the `Provider` tag. Try that.

**Comment by jvoisin** [comment]
There is no `<Provider>` tag on your page, are they?

**Comment by wesharehoodies** [comment]
What about `createStore()` method?

**Comment by jvoisin** [comment]
As state in the [previously linked documentation]( https://github.com/AliasIO/Wappalyzer/wiki/Specification#json-fields ), there is no way to match on Javascript *methods*, only on *global variables*.

**Comment by wesharehoodies** [comment]
@jvoisin https://github.com/reactjs/react-redux/blob/master/src/utils/shallowEqual.js can we use the `const hasOwn = Object.prototype.hasOwnProperty` global?

**Comment by jvoisin** [comment]
`hasOwn` is prone to false positives I guess :/

**Comment by jvoisin** [comment]
Apparently, there is no reliable way to detect Redux.
Except if someone got a nice about how this, I think that we can close this issue, sorry @wesharehoodies

**Comment by wesharehoodies** [comment]
Perhaps we can ask Redux creator if there is a way to reliably detect Redux?

@gaearon Hi sir! We we're wondering if there is a way to reliably detect Redux?

**Comment by AliasIO** [comment]
Would love to include Redux but I don't believe there is a good way to identify it.
