### ISSUE TITLE
Problems Occurred With June 8, 2007 Automatic Upgrade On Firefox re: Icons & Logo

### ISSUE THREAD

**Issue by mjmarrer** [AliasIO/Wappalyzer#1601]
A new tab downloading and installing the update automatically launched while I was in Firefox this morning (somewhere around the 10:00 am EDT time frame).  When it completed I shutdown Firefox and restarted it to ensure that the update was implemented properly.

The first thing I noticed is that all of the technologies it found for a site were no longer shown in the URL area.  That is OK if this feature was replaced by simply the Wappalyzer icon.  The problem is - that icon is not shown either.

In the option settings, selecting and unselecting "Use application icon instead of Wappalyzer logo" makes no difference.  Most of the sites only display a space to the right of existing installed add-on icons (I have Flagfox installed).  Sometimes just one of the technologies found does display - most times not. 

In either case, hovering the mouse over that lone icon or the blank space displays the pop-up window that identifies Wappalyzer, and clicking there does show the list of technologies.

 For example, on my personal site only the Twitter Bootstrap ("B" in a blue box) displays, even though there are three technologies installed (Apache, Bootstrap and jQuery).  The Wappalyzer site itself (https://wappalyzer.com/) only shows the Swiftlet icon, even though clicking there shows eight identified technologies.  And The Drudge Report (http://www.drudgereport.com/) shows a blank space, even though Quantcast, jQuery and jQuery UI were identified.

**Comment by DaAwesomeP** [comment]
@AliasIO there would indeed appear to be a problem with the version just uploaded to AMO. The icon in the URL bar appears to be a blank space sometimes and sometimes not (ex. GitHub seems to produce a blank space, Reddit does not). I did not encounter this bug previously in my own builds.

@mjmarrer Mozilla has deprecated the older addons API in favor of the newer WebExtension API. The older API addons will be disabled in later versions of Firefox, so Wappalyzer has become a WebExtension. Per the WebExtension API, an addon is allowed only one icon to appear in the URL bar (see [`pageAction`](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/pageAction)). The option that you referenced allows for the `pageAction` to either always show the Wappalyzer icon or the icon of the first-detected application.

**Comment by geekyi** [comment]
So this is caused by the switch to WebExtension API? I'm on Firefox Beta 54 btw

**Comment by DaAwesomeP** [comment]
@geekyi Yes, the version just uploaded to AMO makes it now a WebExtension. I've been using my own build of the repo for several weeks prior to now, but I did not experience this bug (the blank space). However, the fact that only one icon appears in the URL bar is not a bug; that is a limitation of WebExtensions.

**Comment by gadcam** [comment]
At [line 9 of popup.js ](https://github.com/AliasIO/Wappalyzer/blob/master/src/drivers/webextension/js/popup.js#L9) there is a typo : <code>interactive</code> is written <code>interacrive</code>.
I don't know if this can be the source of the problem but this need to be fixed.
How could we bypass add-on signing that is preventing tests ? (see https://wiki.mozilla.org/Add-ons/Extension_Signing)

>However, the fact that only one icon appears in the URL bar is not a bug; that is a limitation of WebExtensions.

There is no work-around ? Because if not Wappalyzer will lost a lot of its value for a good part of its users, including me.

**Comment by DaAwesomeP** [comment]
@gadcam as far as I am aware, only one icon can be added to the URL bar per extension. Maybe something can be done to prioritize which icon is chosen for the `pageAction`, or it can cycle it every second or so (that might cause a performance issue though). Unfortunately, Firefox 57 will disable all non-Webextensions.

**Comment by gadcam** [comment]
@DaAwesomeP Maybe we can trick the API by adding just one long image ? I read the API's documentation and I can't find what would be the behaviour of the browser: we need to test it but I can't find how to load an extension with this new extension signing protection..

**Comment by DaAwesomeP** [comment]
@gadcam that's a sneaky trick but fantastic if it works. It will have to be for Firefox and Opera only though because Chrome puts the `pageAction` in the regular toolbar and not the URL bar. That will also be easiest achieved with PNGs only and not SVGs, but the build renders SVGs to PNGs already anyway. I'm not sure what the memory footprint will look like, but it's worth a shot.

Go to `about:debugging` and you can load an unpacked extension. It will be removed next time you restart FF. If you install Firefox Developer Edition, I believe that it either doesn't check for signed extensions or has an `about:config` option to disable signing. I would recommend using a separate profile for Developer Edition though.

**Comment by DaAwesomeP** [comment]
@gadcam supposedly we could create a virtual canvas (as in the `<canvas>` element), put all the images on it side by, and then extract a data URI to use as the icon.

https://stackoverflow.com/questions/6765370/merge-image-using-javascript
https://stackoverflow.com/questions/158750/can-you-combine-multiple-images-into-a-single-one-using-javascript

**Comment by AliasIO** [comment]
That won't work, the dimensions of the icon are fixed.

**Comment by mjmarrer** [comment]
The Firefox plugin was updated this morning.  Now I do see the Wappalyzer logo in the right side of the URL area instead of the blank space.  Thanks!
