### ISSUE TITLE
how to move wappalyzer out of URL

### ISSUE THREAD

**Issue by lvii** [AliasIO/Wappalyzer#1608]
Hi,

After wappalyzer auto updated, it disappeared from vimperactor's status bar.

I have chosen  an  option with **NOT** show wappalyzer in URL bar in the last version of wappalyzer, and moved wappalyzer icon to vimperactor's status bar by Firefox's Customize .

But there was no option about "NOT show wappalyzer in URL bar" in the new version.

MY firefox and plugins versions:

Firefox 53/54
wappalyzer 4.1.3
vimperator 3.16.0

**Comment by AliasIO** [comment]
Firefox has moved to WebExtensions which don't support moving add-on icons being placed elsewhere.

**Comment by lvii** [comment]
@AliasIO 

Other add-ons could show their icon at toolbar in **Firefox 57** like : 

- greasemonkey
- ublock origin
- markdown-here

![img_Firefox_57_addons_icon_at_toolbar](https://i.imgur.com/SAwJEnL.png)

**Comment by AliasIO** [comment]
Because Wappalyzer's functionality is page-specific it uses [pageAction](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/pageAction) instead of [browserAction](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/user_interface/Browser_action). Firefox places pageAction add-ons in the URL bar (Chrome does not). There is no option to make this configurable by users.
