### ISSUE TITLE
Wappalyzer does not work on TorBrowser

### ISSUE THREAD

**Issue by LoHub** [AliasIO/wappalyzer#1647]
Hi,
I have an issue with the Wappalyzer add-on on TorBrowser 7.0.2, which is based on  Firefox 52.2 (64 bit)
The add-on does not display the technologies used on website in the top bar. There is absolutely, no difference with and without Wappalyzer.
If you need more information, you can contact me.
Exuse me for my english, it is not my mother tongue.

**Comment by Retia-Adolf** [comment]
Still doesn't work even on Firefox 67.0b7 (64-bit), thanks to above I recalled I have turned FirstPartyIsolation on someday, and maybe that's why.. I don't know why this should break extensions from working correctly. ([ViolentMonkey](https://violentmonkey.github.io/) has a option as workaround for this)
