### ISSUE TITLE
Having a technology name in the page content puts it to the Wappalyzer list

### ISSUE THREAD

**Issue by s2qts** [AliasIO/Wappalyzer#1729]
I've noticed this bug on StackOverflow.

There's a post which mentions Backbone.js and Wappalyzer shows it in the list of Javascript Frameworks.

You can check the bug here:
https://stackoverflow.com/questions/46157943/csrf-verification-failed-django-rest-and-backbone-js

**Comment by AlexByte** [comment]
The question on SO is not relevant to Wapplazyer.

**Comment by AlexByte** [comment]
Give links which are affected by this bug.

**Comment by Hisagr** [comment]
The post itself has nothing to do with this issue. It just contains the string "Backbone.js" which recognizes by Wappalyzer as a used technology. You can also check [any other post](https://stackoverflow.com/search?q=backbone.js) about backbone.js to see this bug present. 
Attaching a screenshot also.
![untitled](https://user-images.githubusercontent.com/11569140/30329965-e2a7f530-97a1-11e7-82a0-3ad5bfb7213e.png)

**Comment by gadcam** [comment]
The problem here is a bit more complex.
What is causing this false positive is that <code>Backbone.js</code> is a tag of the question. (and the same explanation apply if the referral page URL contains backbone.js)
So then you have DoubleClick and Adzerk scripts that are loading some other scripts on page load according to the tag of the question.
Which looks like that:
```js
<script src="https://securepubads.g.doubleclick.net/gampad/ads?gdfp_req=1&amp;correlator=3451486646948005&amp;output=json_html&amp;callback=googletag.impl.pubads.callbackProxy1&amp;impl=fifs&amp;json_a=1&amp;eid=108809107%2C21060692&amp;sc=1&amp;sfv=1-0-10&amp;iu_parts=248424177%2Cstackoverflow.com%2Clb%2Cquestion-pages%2Csb&amp;enc_prev_ius=%2F0%2F1%2F2%2F3%2C%2F0%2F1%2F4%2F3&amp;prev_iu_szs=728x90%2C300x250%7C300x600&amp;cust_params=Registered%3Dtrue%26so-tag%3Djavascript%252Cpython%252Cdjango%252Cbackbone.js%26X-Site%3Dserverfault.com%252Cstats.stackexchange.com%252Cunix.stackexchange.com%252Csoftwareengineering.stackexchange.com%252Candroid.stackexchange.com&amp;cookie=ID%3D8c32419c8142c888%3AT%3D1502208015%3AS%3DALNI_Mb_swgIhecg1JMew7SlXe2GMIUNsg&amp;abxe=1&amp;lmt=1505235120&amp;dt=1505235120506&amp;frm=20&amp;biw=1519&amp;bih=460&amp;oid=3&amp;adxs=0%2C990&amp;adys=0%2C151&amp;adks=58773763%2C228937067&amp;gut=v2&amp;ifi=1&amp;u_tz=120&amp;u_his=1&amp;u_h=864&amp;u_w=1536&amp;u_ah=824&amp;u_aw=1536&amp;u_cd=24&amp;u_sd=1.25&amp;flash=0&amp;url=https%3A%2F%2Fstackoverflow.com%2Fquestions%2F46157943%2Fcsrf-verification-failed-django-rest-and-backbone-js&amp;dssz=31&amp;icsg=34&amp;std=14&amp;vrg=147&amp;vis=1&amp;ga_vid=380229078.1501462052&amp;ga_sid=1505235121&amp;ga_hid=1934611349">
</script>
```
and
```js
<script type="text/javascript" async="" src="https://engine.adzerk.net/ados?t=1505235119790&amp;request={&quot;Placements&quot;:[{&quot;A&quot;:22,&quot;S&quot;:8277,&quot;D&quot;:&quot;adzerk2138886854&quot;,&quot;AT&quot;:4,&quot;Z&quot;:[43]},{&quot;A&quot;:22,&quot;S&quot;:8277,&quot;D&quot;:&quot;adzerk691563963&quot;,&quot;ATA&quot;:[5,17,2221,1129,43],&quot;Z&quot;:[45]}],&quot;Keywords&quot;:&quot;javascript%2Cpython%2Cdjango%2Cbackbone.js%2Cx-user-registered%2Cx-cross-site-serverfault.com%2Cx-cross-site-stats.stackexchange.com%2Cx-cross-site-unix.stackexchange.com%2Cx-cross-site-softwareengineering.stackexchange.com%2Cx-cross-site-android.stackexchange.com&quot;,&quot;Referrer&quot;:&quot;&quot;,&quot;IsAsync&quot;:true}">
</script>
```
So the src part of the script tag is containing <code>Backbone.js</code> (or to be more accurate something like [this](https://github.com/AliasIO/Wappalyzer/blob/master/src/apps.json#L859): <code>backbone.*\\\\.js</code>) which is causing the wrong detection.

So thank you for the bug report we need to make the regex more specific by : 
- adding something like a blackslash before backbone and the same apply for a lot of other library with too simple patterns
- be more specific with the part <code>.*</code>

Ps: using <code>.*</code> or <code>.+</code> is a **very** bad practice and we should use them only in very specific situations and I see we have 100 usages of them

**Comment by AlexByte** [comment]
> be more specific with the part .*
This does not apply to this issue.

**Comment by gadcam** [comment]
You're right : I was just suggesting that we solve both problems in one commit, plus I don't know if we couldn't trigger an even more complex situation were this part will be faulty. (I mean with DoubleClick and Adzerk)

**Comment by AlexByte** [comment]
> blackslash before backbone

Why backslash is necessary?

**Comment by gadcam** [comment]
My bad, I wrote the end of my post a bit too fast I meant a slash <code>/</code> but we would rather need something like <code>(?:^|/)</code>

**Comment by AlexByte** [comment]
> apply for a lot of other library with too simple patterns

It is possible to add \b to the beginning of the pattern in the https://github.com/AliasIO/Wappalyzer/blob/a05d78e47d6eeb4c8046a03f437bb38baed3cc8a/src/wappalyzer.js#L410

**Comment by kyletaylored** [comment]
Seems like this has been fixed since 2017.
