### ISSUE TITLE
EF.JS getting randomly detected.

### ISSUE THREAD

**Issue by Zaseth** [AliasIO/Wappalyzer#1753]
EF.JS suddenly gets detected on pages where it does not even run on.

**Comment by AlexByte** [comment]
Give examples

**Comment by Zaseth** [comment]
https://pastebin.com/raw/wVLECKcY

This will show EF.JS while it's just a .txt

**Comment by AlexByte** [comment]
Ep.js?

**Comment by Zaseth** [comment]
Oh typo. Doesn't matter though. Wappalyzer just detects a technology on a
blank txt file

**Comment by q--** [comment]
I [corrected the spelling](https://pastebin.com/raw/HyyZQLKu) in your example, but I'm not getting an ef.js detection; the extension doesn't detect anything for me, and the bookmarklet gives only CloudFlare, HTTP/2 and Nginx.

I see a potential for false detections though, because one of its detection rules is looking for a variable named `ef`, which is so short that it'll likely be among the variable names generated by the Google Closure Compiler (which [can](https://developers.google.com/closure/compiler/docs/api-tutorial3) optimize JavaScript by replacing JavaScript variable and function names with the shortest variable name available, so `MyFunction` becomes `a`, `MyNextFunction` becomes  `b` etc.).

Still, that doesn't yield any clues as to why you're seeing ef.js detected for a text file.

**Comment by gadcam** [comment]
I also agree : what you describe should be a problem with the cache maybe, not detection directly.
However we need to remove the <code>ef</code> pattern.

**Comment by Zaseth** [comment]
It's even adding an icon to it. Deleting this would fix the issue.

**Comment by jvoisin** [comment]
This has been addressed in 3c707bd42. This issue can be closed.

**Comment by AlexByte** [comment]
@jvoisin why do you refer to commits instead of pull-request?
