### ISSUE TITLE
Wrong category for GitHub Pages?

### ISSUE THREAD

**Issue by q--** [AliasIO/Wappalyzer#1909]
Currently, the categories for GitHub Pages are 'Blog' and 'CDN'. I think the first is dubious, because many of the websites hosted through GitHub pages aren't blogs at all. Also, unlike something like WordPress, GitHub pages wasn't specifically designed with blogging in mind (through you can certainly host a blog on it).

As for the CDN category, well, that shouldn't be 'GitHub Pages' but 'Fastly', as this `dig` lookup shows:

```
id 22864
opcode QUERY
rcode NOERROR
flags QR RD RA
;QUESTION
facebook.github.io. IN A
;ANSWER
facebook.github.io. 3599 IN CNAME sni.github.map.fastly.net.
sni.github.map.fastly.net. 23 IN A 151.101.1.147
sni.github.map.fastly.net. 23 IN A 151.101.65.147
sni.github.map.fastly.net. 23 IN A 151.101.129.147
sni.github.map.fastly.net. 23 IN A 151.101.193.147
;AUTHORITY
;ADDITIONAL
```

I think GitHub Pages belongs either in the category 'CMS' or in the category 'Miscellaneous' (since Git is just the means by which content is published, I'm leaning towards Miscellaneous - after all, other websites have their content uploaded through FTP and an FTP server isn't a CMS either.

What do you think?

**Comment by jvoisin** [comment]
[Github pages]( https://pages.github.com/ ) is kind of a CDN: you put your data there, and it's served as web-content. But I agree that it's a bit more than that :/

**Comment by kyletaylored** [comment]
Github Pages probably falls more in the line of Netlify. And even for Netlify, they're marked as a Web Server, but they actually use [Nginx as the server](https://medium.com/nyc-planning-digital/o-hai-netlify-120c9f961922), they just overwrite the header. They're more like a PaaS for static sites. But Netlify DOES provide their own CDN called Netlify Edge, so that category is correct.

I'm going to make these category updates.
