### ISSUE TITLE
I think that the Angular filter isn't working

### ISSUE THREAD

**Issue by EddyVinck** [AliasIO/wappalyzer#2087]
It seems strange to me that AngularJS has 640,000 websites but Angular (the latest version) has none.

https://www.wappalyzer.com/technologies/angularjs
https://www.wappalyzer.com/technologies/angular

**Comment by gadcam** [comment]
We have only one pattern for Angular which is a[ HTML pattern ](https://github.com/AliasIO/Wappalyzer/blob/master/src/apps.json#L634):
```regex
<[^>]+ ng-version="([\d.]+)"
```
when we have a lot of differents ones for AngularJS

```
"js": {
	"angular": "",
	"angular.version.full": "(.*)\\;version:\\1"
	},
"script": [
	"angular(?:\\-|\\.)([\\d.]*\\d)[^/]*\\.js\\;version:\\1",
	"/([\\d.]+(?:\\-?rc[.\\d]*)*)/angular(?:\\.min)?\\.js\\;version:\\1",
	"angular.*\\.js"
]
```

HTML patterns are the least reliable ones and may not match not because they are not good but because the match is in [the middle of the page](https://github.com/AliasIO/Wappalyzer/blob/master/src/drivers/webextension/js/content.js#L8) and we analyse only the part around it
```js
    if ( html.length > 100 * 1024 ) {
      html = html.substring(0, 50 * 1024) + html.substring(html.length - 50 * 1024, html.length);
}
```

**Comment by gadcam** [comment]
74bb8fa should help with this matter.

**Comment by tayambamwanza** [comment]
@gadcam This continues to be an issue unfortunately :\
