### ISSUE TITLE
www.greenhouse.io and Yii framework detected Bug

### ISSUE THREAD

**Issue by archwhite** [AliasIO/Wappalyzer#2242]
**I want report a bug**

**What is the current behavior ?**
Extension shows greenhouse uses Yii/PHP

![image](https://user-images.githubusercontent.com/7243155/38870319-237203ee-4256-11e8-843d-bdc93ca73f52.png)

**What is the expected behavior ?**
It seems greenhouse uses Rails.
see here https://www.quora.com/What-is-Greenhouses-technology-stack
and here https://builtwith.com/?https%3a%2f%2fwww.greenhouse.io%2f

**Which versions of Wappalyzer, and which browser / OS are affected by this issue ? Did this work in previous versions ?**
Wappalyzer version is 5.4.11, Win 7,  Chrome 65.0.3325.181

**Comment by gadcam** [comment]
The detection seems correct to me : 
Yii is detected because of the detection Craft CMS which is detected via a cookie named <code>CraftSessionId</code>.
And Yii is implying the use of PHP.

> see here https://www.quora.com/What-is-Greenhouses-technology-stack
>>Answered Aug 10 2016 

So I do not know if we can still take this information as reliable.

>and here https://builtwith.com/?https%3a%2f%2fwww.greenhouse.io%2f

Here Wappalyzer seems just to do a better job than BuiltWith : they also detected Craft CMS but they did not infer from this information that Yii was also used and so PHP ;)
