### ISSUE TITLE
opt in instead of hidden opt out of data collection

### ISSUE THREAD

**Issue by treakiandroid** [AliasIO/Wappalyzer#2365]
could your addon "ask" before enabling sending data back to your servers instead of "hiding" some option to opt out from it. Also i miss in this preferences section just below the "checkbox of choice" a way to look up your privacy statement which data are collected in which way send where to and stored where to for how long and so on...

thanks in advance

**Comment by AliasIO** [comment]
The [privacy policy](https://www.wappalyzer.com/privacy) is linked from the extension pages. The tracking is prominently disclosed on the Firefox add-on page, I might add a line on the Chrome Web Store and download page as well. It will remain opt-out however.

**Comment by jvoisin** [comment]
I don't think that this is GDPR-compliant, and since odds are that you're selling personal informations from EU citizen, you must comply with it.

Also, the privacy policy doesn't explain what data are collected, what they are used for, with whom they are shared, how and under what condition, … it's also non-obvious how to opt-out of the collection process (it should be as easy to opt-in than to opt-out).
