### ISSUE TITLE
[bug][privacy] Tracking data sent while the tracking option is disabled

### ISSUE THREAD

**Issue by cnotin** [AliasIO/Wappalyzer#2531]
This is a *bug* report in the *Firefox (at least) WebExtension*

**What is the current behavior ?**
I have unticked the "send anonymous reports..." (tracking option).
However I see POST requests to `ad.wappalyzer.com/log/wp/` with my history.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a demo of the problem.**
Settings:
![image](https://user-images.githubusercontent.com/550823/47780021-ce8bc000-dcfa-11e8-949c-4c87e549d1b1.png)

POST request:
![image](https://user-images.githubusercontent.com/550823/47780083-f3803300-dcfa-11e8-958b-046a17add3ae.png)

**What is the expected behavior ?**
No tracking data should be sent if the checkbox is unticked.

**Which versions of Wappalyzer, and which browser / OS are affected by this issue ? Did this work in previous versions ?**
Wappalyzer (5.5.5)
Firefox 63.0 (64 bits)
Windows 10

**Debugging steps**
If it helps you I have used the extensions debug feature of Firefox. And I have observed the following (executed in the context of the extension of course):
![image](https://user-images.githubusercontent.com/550823/47780192-3510de00-dcfb-11e8-89c4-5c457899992e.png)

The code is similar to the one observed in `driver.js`:
```js
wappalyzer.driver.ping = (hostnameCache = {}, adCache = []) => {
  getOption('tracking', true)
    .then((tracking) => {
      if (tracking) {
        if (Object.keys(hostnameCache).length) {
          post('https://api.wappalyzer.com/ping/v1/', hostnameCache);
        }

        if (adCache.length) {
          post('https://ad.wappalyzer.com/log/wp/', adCache);
        }

        setOption('robotsTxtCache', {});
      }
    });
};
```

I suppose that there is a bug somewhere in `function getOption(name, defaultValue = null)` in `driver.js`

Do not hesitate to ask if you need more information.

**Comment by DanH42** [comment]
I (try to) keep all three options disabled, and they've silently re-enabled themselves multiple times today alone.

**Comment by DanH42** [comment]
#2490 from a couple months ago included https://gfycat.com/TenderNeighboringBudgie which shows the issue being triggered by simply re-launching Chrome. This seems to line up with my experience as well.

The tracking feature is a big problem to have enabled by default regardless, as it logs every URL visited by the user and sends them to a third party server. Regardless of what you claim to do with this information, collecting a user's entire browsing history is incredibly irresponsible and puts hundreds of thousands of users at risk in the event that your servers should be compromised. Claiming that this can be done "anonymously" is an outright lie due to the amount of PII that is often included in URLs and query parameters by some sites. Sometimes authentication information can even make it into URLs, even if it's generally considered bad practice to do so. While malice may not have been the intent, the default behavior of this extension is indistinguishable from spyware.

**Comment by AliasIO** [comment]
This should be fixed in https://github.com/AliasIO/Wappalyzer/commit/ea900bfd1f1855424f1fd346f3ced47694d8711f#diff-810b4f4b3efe5b5bc0b99ade94beeccc.

@DanH42 I hear you. No IP addresses are being stored though, in accordance with [privacy policy](https://www.wappalyzer.com/privacy). I do apologise for the extension settings not being respected, that shouldn't have happened.

**Comment by jvoisin** [comment]
Shouldn't we test this someone in the testsuite?

**Comment by DanH42** [comment]
It would also make a lot of sense if [options.js](https://github.com/AliasIO/Wappalyzer/blob/master/src/drivers/webextension/js/options.js#L8) used the same logic for `getOption` as [driver.js](https://github.com/AliasIO/Wappalyzer/blob/master/src/drivers/webextension/js/driver.js#L26) so that discrepancies like this don't continue happening in the future.

**Comment by AliasIO** [comment]
Thanks @DanH42, I just pushed v5.6.1 to fix these.

**Comment by AliasIO** [comment]
@jvoisin I'm all for it, of course. We don't have tests for the WebExtension driver currently.

**Comment by wheelq** [comment]
Hmm, with this option, either enabled or disabled, I can't see any POST requests to ad.wappalyzer.com/log/wp/ in my history....

**Comment by jabberwock** [comment]
Why is this still enabled by default, with no warning or consent? This causes me to want to uninstall this plugin and warn all of my colleagues to do the same.
