### ISSUE TITLE
Can't Detect Vue.Js Apps Created with Vue-Cli

### ISSUE THREAD

**Issue by muraterzioglu** [AliasIO/wappalyzer#2603]
**Do you want to request a *feature*, a *new application detection* or report a *bug*?**
Report a bug 

**Is your issue about WebExtension driver (Chrome & Firefox), the website, the NPM driver or the bookmarklet ?**
About WebExtension at Chrome

**What is the current behavior ?**
In localhost when I was run my Vue.js Application, Extension Shows to Me I'm Using Express

**If the current behaviour is a bug, please provide the steps to reproduce and if possible a demo of the problem.**
-----

**What is the expected behaviour?**
It should be shown Vue.Js and Node.js. I didn't use Express anytime.

**Which versions of Wappalyzer, and which browser / OS are affected by this issue? Did this work in previous versions ?**
Chrome Latest Stable Version (Extension is stable and last version)
O/S: Ubuntu 18.04 LTS
I don't know when to start developing my personal website I'm probably using the latest version of the extension

**Personal Question**
I created my application with Vue-CLI and run with `npm run serve`. Is it possible to install express by default and see this by the extension?

![Screenshot from my website from localhost](https://user-images.githubusercontent.com/34911048/51494633-56e5a280-1dca-11e9-8f25-51c37f88a9cd.png)

**Comment by q--** [comment]
[Seems like Vue-CLI uses Express under the hood](https://github.com/vuejs/vue-cli/search?q=express&unscoped_q=express), so that correction is correct.

As for why it doesn't detect Vue... The rules for Vue are [here](https://github.com/AliasIO/Wappalyzer/blob/master/src/apps.json#L11630), I'd have to see any ways to detect Vue that Wappalyzer is missing.

I did notice a bug in the HTML rule though, I've made  pull request #2825 to fix that
