### ISSUE TITLE
Basecamp PDF preview conflict using Chrome and Wappalyzer

### ISSUE THREAD

**Issue by pablofrijole** [AliasIO/Wappalyzer#2726]
Hello, first time posting an issue. Here goes:

I am using Chrome for Mac, the most recent version, 75.0.3770.100 (Official Build) (64-bit). I noticed in the last version that when I logged in to Basecamp and had the Wappalyzer extension running, I was no longer able to preview PDF files that were embedded within a thread. 

When I turned off Wappalyzer, the issue ceased to exist and I could preview PDFs appropriately. 

If there's anyone that can help with this bug, much appreciated! ;) 

![Screenshot 2019-06-27 15 25 18](https://user-images.githubusercontent.com/51139873/60305035-18f82780-98f0-11e9-9ba6-09bea6fa84e1.png)

**Comment by kyletaylored** [comment]
What version of Basecamp are you using?

**Comment by pablofrijole** [comment]
Basecamp 2. 

 

-- 

Paul J. Bean

CEO

AGP Digital Marketing, LLC

Toll Free 888.896.7770, x1

Web www.StudioAGP.com

**Comment by kyletaylored** [comment]
If this is still happening, could you do a little debugging on your own using the background.html file as part of the debugger? Unfortunately I can't test this because I don't have a Basecamp 2 account, so this will be pretty hit or miss.

If it does still happen - feel free to reopen this issue with more info!
