### ISSUE TITLE
Firefox+Twitter drops connection

### ISSUE THREAD

**Issue by humunuk** [AliasIO/wappalyzer#2735]
**Do you want to request a *feature*, a *new application detection* or report a *bug*?**
BUG

**Is your issue about WebExtension driver (Chrome & Firefox), the website, the NPM driver or the bookmarklet ?**
WebExtension driver

**What is the current behavior ?**
When ever I open twitter while having wappalyzer enabled all firefox windows loose the ability to connect to internet and I have to reopen firefox again (close all firefox and reopen).

**If the current behavior is a bug, please provide the steps to reproduce and if possible a demo of the problem.**

**What is the expected behavior ?**
Dont drop the connection if opening twitter while having wappalyzer enabled

**Which versions of Wappalyzer, and which browser / OS are affected by this issue ? Did this work in previous versions ?**
Wappalyzer version: 5.8.3
Firefox version: 67.0.4
The problems started occuring lately (few days top).

**Comment by baptx** [comment]
I have the same problem and was going to report it. If we use Twitter while logged in, we have to disable Wappalyzer addon, otherwise it blocks the network connection for all tabs / windows of Firefox (Internet connection as well intranet connection, for example if we want to access a web server running on localhost). The connection is still blocked after closing the Twitter tab / window or disabling the addon, we have to restart the browser.
Does someone know why it happens and do you have a fix?

**Comment by baptx** [comment]
Not stale or at least a comment explaining why the issue happened is welcome.

**Comment by AliasIO** [comment]
Is this still an issue? I haven't observed this myself.

**Comment by baptx** [comment]
@AliasIO I don't know since I stopped using the addon when I had the issue. Do you know what part of the addon code was causing the issue and if a fix was deployed?

**Comment by AliasIO** [comment]
A lot has changed but it may have been related to inspecting SSL certificates, which was blocking and has since been reverted. Other functions have also been updated to be async and non-blocking. I use Firefox and Twitter and haven't seen this behaviour.
