### ISSUE TITLE
JS regex [^]

### ISSUE THREAD

**Issue by kkaiser** [AliasIO/wappalyzer#2840]
Hello,

Thanks for this great library. 

Usually the regex`[^ab-d]` matches one character except: a, b, c, d. But in JS there is this special pattern `[^]` that matches any character, including newline. 

Would you consider to change it so the regexes in [apps.json](https://github.com/AliasIO/Wappalyzer/blob/master/src/apps.json) are compatible with other languages? It's an invalid regex in python for example. Instead of `[^]` the pattern `(?:.|\n)` can be used.

regards,
Kevin

**Comment by kyletaylored** [comment]
Hey Kevin,

Sorry, I know that can be frustrating. Unfortunately, everything in this repo is based on JavaScript, so that is the bounds of limitation we're working with, and introducing some kind of library to convert other Regex formatting isn't really ideal. I do recommend using [regexr.com](https://regexr.com) to test your Regex!

**Comment by AliasIO** [comment]
If there's a simple way to make the regular expressions more universal, I'm all for it. Is it just `[^]` that's an issue?

**Comment by q--** [comment]
https://stackoverflow.com/a/55149095

Replacing it with `[\\s\\S]` would work.

There are currently three patterns using `[^]`, so it wouldn't be too hard to replace. Of course, any third-party program using Wappalyzer's patterns should be able to carry out the search/replace itself without too much effort.
