### ISSUE TITLE
Corrupted in Edge Chromium

### ISSUE THREAD

**Issue by riipandi** [AliasIO/wappalyzer#2927]
**Platform**
Which platform does the bug apply to?

* Microsoft Edge Chromium Extension
* MacOS Catalina and Microsoft Windows

**Describe the bug**
![screenshot](https://user-images.githubusercontent.com/921834/73824039-06ea4a00-482c-11ea-98c6-4e196f730bf2.png "Error in Edge Chromium")

**Additional context**
I tried to repair, but it still happens.

**Comment by Uriel1339** [comment]
I'm getting the same exact error.

**Comment by frederickalcantara** [comment]
I agree, I am also having issues with wappalyzer in the Edge Chromium browser as well.

**Comment by unbekannt3DE** [comment]
For me installing the chrome web store version fixes it atm

**Comment by eristavi** [comment]
Exact same error here. It shows the error messages sometimes though. It should be fixed asap as Edge seems to be an excellent alternative to Chrome.

**Comment by AliasIO** [comment]
The latest version was just approved, please let me know if that fixes it.

**Comment by Uriel1339** [comment]
@AliasIO - nope, still breaks.

**Comment by riipandi** [comment]
Same, still break for me.

**Comment by TheUnriashol** [comment]
Currently also getting this issue. I can repair it and it re-enables the plugin. Once I reload a website and click on the plugin it disappears from the toolbar and it shows the same error message again in the extensions overview.

**Comment by TheUnriashol** [comment]
Just saw that the plugin got upgraded to 5.9.30 and got really excited since it was working while I stayed on Google. I went to YouTube and it immediately crashed again and shows the error message in the extensions overview.

So I repaired it and tried not going to YouTube but other websites and it seems to work. The only weird thing is that when going to Facebook for example it cant detect any technologies at all. And as soon as I go back to YouTube it crashes again. Seems like some sort of technology that is running on YouTube causes Wappalyzer to crash.

**Comment by AliasIO** [comment]
I'm unsure how to debug this as the console crashes along with the extension. I noticed on some sites it works fine (e.g. https://example.com), on some it crashes when the popup opens (https://www.wappalyzer.com) and on others it crashes immediately (https://www.youtube.com).

It only happens when the extension is installed from the Edge store. No issues installing it locally or from the Chrome store.

**Comment by MarkSky** [comment]
After updating to 5.9.30, It's still broken.

**Comment by AliasIO** [comment]
Microsoft has assured me they fixed the issue on their end. A new version is waiting approval now, as soon as that becomes available this should be resolved.

**Comment by AliasIO** [comment]
This has now been resolved.
