### ISSUE TITLE
Clarify terms of license

### ISSUE THREAD

**Issue by oxr463** [AliasIO/wappalyzer#2977]
See: https://www.gnu.org/licenses/identify-licenses-clearly.html

SPDX: [GPL-3.0-only](https://spdx.org/licenses/GPL-3.0-only.html), or [GPL-3.0-or-later](https://spdx.org/licenses/GPL-3.0-or-later.html)

**Comment by kingthorin** [comment]
The license was changed?
![image](https://user-images.githubusercontent.com/7570458/78822448-13645d80-79a9-11ea-9bec-28ffc3a05667.png)

**Comment by oxr463** [comment]
That's not good..

**Comment by oxr463** [comment]
See also: https://opensource.stackexchange.com/q/9557/8868

**Comment by q--** [comment]
Yeah, I don't think this is going to work, legally speaking. You're free to distribute your own code under whatever license you'd like, but all Wappalyzer project contributors through the years never assigned copyright to you or at least the right to re-license their code. Though because of the LICENSE file included with the project, I think that counts as an implicit agreement to allow our contributions to be used under the GPL.

(The previous license change from MPL 2.0 to GPL was less problematic, as the MPL 2.0 allows MPL-licensed code to be incorporated in GPL-licensed projects, subject to certain conditions; see [1.12 and 3.3](https://choosealicense.com/licenses/mpl-2.0/))

Specifying that all future contributions are under the MIT license wouldn't be a problem either. As for existing code, I'm pretty sure you'll either have to get permission from everyone who contributed code to the project up to now or remove said code from the project. IANAL though.

Not that I would necessarily object to re-licensing my contributions to Wappalyzer under the MIT license (haven't made up my mind on that yet), but I'm far from the only contributor.

**Comment by AliasIO** [comment]
I'm aware the licenses aren't fully compatible but didn't expect much resistance to change to a more liberal one. I don't think GPL is well suited as its main point (from what I understand) is that derived, distributed works must be made publicly available under the same license. Wappalyzer isn't typically being distributed in the same way that Linux or Git are so this is not a scenario that ever really happens. What's more important is that authors retain their copyright and that doesn't change. The MIT license is less restrictive, making it easier for others to use the code. 

Most of the code in this repository is my own, with the exception of translations and many of the of patterns in `apps.json`. I could keep those under the old license or re-implement contributions myself if any authors object to the change but I'm hoping that won't be necessary.

I'm happy discuss any arguments against changing to MIT. It's more in line with open-source ideology which hopefully everyone agrees is a good thing.

**Comment by oxr463** [comment]
> I'm happy discuss any arguments against changing to MIT. It's more in line with open-source ideology which hopefully everyone agrees is a good thing.

Regarding ideology, please see: https://www.gnu.org/philosophy/open-source-misses-the-point.en.html

In any case, there is nothing wrong with changing the license to whatever you want it to be; but it isn't as simple as changing the `LICENSE` file. Re-licensing a project properly is not a trivial task.

Wappalyzer is a mature project used by quite a decent user base. Looking at the [Contributors list](https://github.com/AliasIO/wappalyzer/graphs/contributors) reveals dozens of people who have made commits to the source.
