### ISSUE TITLE
Move browser ext icon to URL location bar Back in Firefox

### ISSUE THREAD

**Issue by realstephenzhao** [AliasIO/wappalyzer#3249]
**Is your feature request related to a problem? Please describe.**
Please move browser ext icon to URL location bar Back in Firefox, It always stayed in URL bar till version 6.0.16.

**Describe the solution you'd like**
Move ext icon back to URL bar just like before

**Describe alternatives you've considered**
No alternate.

**Additional context**
I know Google Chrome doesn't allow to place ext icon to location bar, but Firefox does allow it.

**Comment by AliasIO** [comment]
This was done for a few reasons: `browserAction` is more appropriate for the type of extension, Safari compatibility and to enable the badge showing the number of identified technologies. Badges are not supported on `pageAction`.

https://developer.chrome.com/extensions/browserAction
https://developer.chrome.com/extensions/pageAction

**Comment by realstephenzhao** [comment]
I hope I can never update to version 6.0.16 in Firefox. Actually I don't need number badge and don't really care about Safari. I just want to save my space of addon tool bar.
It's a pity I may not get unique UI on Firefox any more.

**Comment by vensauro** [comment]
we can make a fork of this? how i can change this?

**Comment by MarxCartoonee** [comment]
The badge doesn't really provide any useful information, plus from a UX perspective it was more convenient for the button to be in the URL bar for a few reasons:
- it's much easier to associate it with the opened website
- it's easy to spot with a quick glance, making it easy to find when you need it
- it doesn't draw unwanted attention when you don't need it since on a daily basis the user is likelier to look either at the url or the buttons to the left or right of it

I feel like this should either be configurable or support both out of the box similar to how Multi-Account Containers does it.

**Comment by AliasIO** [comment]
By default the icon doesn't change any more when a technology is detected because people often couldn't find the extension. The badge is there to indicate that there is information. I wouldn't mind making it an option but switching between `pageAction` and `browserAction` dynamically isn't possible.

**Comment by swrobel** [comment]
@AliasIO what I'm trying to understand is why you completely changed the extension presentation in a patch version release 🤔

**Comment by DanH42** [comment]
I just got this update today and I was also quite surprised and confused by this change, especially since it's not even mentioned in the release notes for 6.0.16. Badge text is almost always just visual clutter, so at the very least there needs to be an option to disable it.

I'd also like to throw out a reminder that Chrome is not the only browser, and that even though Google effectively killed Page Actions in their browser 5 years ago, they do still show up normally in multiple other browsers to this day. Restoring support for Page Actions was one of the many reasons I switched away from Chrome in the first place. I would argue that in those browsers that still support them, Page Actions _do_ make more sense for an extension like Wappalyzer, which is always going to be showing page-specific information (and doesn't need to show its icon at all if it's got nothing to say). @AliasIO seemed to agree with this in #765, but apparently no longer does.

I'll admit I don't have a perfect solution to suggest for making everyone happy if other people really want dynamic badge text, since as it's been mentioned in both this thread and the original from 2015, extensions unfortunately still can't dynamically switch between page/browser actions, and Google never gave pageActions access to badge-related APIs even though they're otherwise functionally identical. It just sucks that non-Chrome users have to live with the consequences of Google's bad decisions from half a decade ago.

As for reverting to 6.0.15, that's really only a temporary workaround, since the main thing that changes in new releases is technology detection, and you'd be missing out on all those updates. I'm sure it would be a bit of a pain to maintain, but for what it's worth, I'd use a second Page Action version of the extension if it existed.

**Comment by AliasIO** [comment]
I'm happy to add an option to disable the badge to reduce clutter. And in case it's not clear, there is a setting to show the technology icon instead of the Wappalyzer logo.

My main reason for switching is that people would often complain about not being able to find the extension because the icon changes dynamically. With a static icon it's not clear when that there is information in the popup and the badge solves that. Looking at extensions like uBlock Origin and LastPass, they all use `browserAction` even though they show page-specific information.

I'm a Firefox user myself and I've always liked having the extension in the address bar, although it was much more useful before WebExtensions when multiple icons could be shown. Feedback on the change to a static icon and badge has generally been positive but I know it doesn't make everyone happy. For me as a maintainer having the extension work consistently across platforms is also a positive. Unfortunately it's not possible to have it both ways.

**Comment by AliasIO** [comment]
Option to disable the badge added in 59240ffb939cba87ed4e6ccd76720bd4fc90a481.

**Comment by lilydjwg** [comment]
I'm downgrading to 6.0.15. Maybe I will remove this extension in the future because I'm not a heavy user of it.

I'm a Firefox user for a long time and I hate being reminded of the existence by webext icons for those functionalities that I neither see or click a lot. I like the old times that extensions just worked without me noticing until it was broken.

Now I can get rid of the badge text, but what about the icon? The static one isn't very useful and the dynamic one will make me wonder what extension is this.

I have flagfox and Feeds in page in my url currently. They share a common feature: they are dynamic. Wappalyzer used to but it's a different beast now.

**Comment by watain666** [comment]
> I'm downgrading to 6.0.15. Maybe I will remove this extension in the future because I'm not a heavy user of it.
> 
> I'm a Firefox user for a long time and I hate being reminded of the existence by webext icons for those functionalities that I neither see or click a lot. I like the old times that extensions just worked without me noticing until it was broken.
> 
> Now I can get rid of the badge text, but what about the icon? The static one isn't very useful and the dynamic one will make me wonder what extension is this.
> 
> I have flagfox and Feeds in page in my url currently. They share a common feature: they are dynamic. Wappalyzer used to but it's a different beast now.

6.0.15 is unavailable at add-on store, I wonder where can download this version?
thanks

**Comment by lilydjwg** [comment]
> 6.0.15 is unavailable at add-on store, I wonder where can download this version?

I have uninstalled wappalyzer for quite some time but I find it from my backup: [wappalyzer-6.0.15-fx.zip](https://github.com/AliasIO/wappalyzer/files/8321729/wappalyzer-6.0.15-fx.zip)

**Comment by watain666** [comment]
> > 6.0.15 is unavailable at add-on store, I wonder where can download this version?
> 
> 
> 
> I have uninstalled wappalyzer for quite some time but I find it from my backup: [wappalyzer-6.0.15-fx.zip](https://github.com/AliasIO/wappalyzer/files/8321729/wappalyzer-6.0.15-fx.zip)
> 
> 

Thanks a lot!🙏
