### ISSUE TITLE
Bootstrap detects wrong version number

### ISSUE THREAD

**Issue by honjes** [AliasIO/wappalyzer#3401]
Platform
Which platform does the bug apply to?

- WebExtension (Google Chrome, Mozilla Firefox)

Describe the bug
Bootstrap shows the wrong version-number

To Reproduce

1. Go to 'https://github.com/'
2. Check the Wappalyzer predictions for Bootstrap detection
3. See error

Expected behavior
Should show no version number

Additional context
Also on this site 'https://arastta.org/get-involved''

**Comment by kyletaylored** [comment]
Looking at the rule, it's kind of finicky but there isn't really any other option. You're more likely to get an actual version of Bootstrap because most people likely use CDN-linked assets (like BootstrapCDN), and the main rare case would be if the assets were custom compiled with an arbitrary hash, which then shows up as the version number (see screenshot below).

So it would either be, accept the small risk of a wrong version number, or remove the version completely - and in this case, I think it would be acceptable to leave it as-is.

![image](https://user-images.githubusercontent.com/1759794/107313648-9dada000-6a58-11eb-8190-621ea7ac1708.png)

**Comment by danbrady** [comment]
If you look at https://www.booker.senate.gov, you'll see Wappalyzer identify Bootstrap 4.7.0, which doesn't exist. Investigating the source, it looks like it's using 4.3.1.

It's possible that it's picking up the version from the Bootstrap CDN link to Font Awesome: https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css

(Apologies if this is hijacking this issue, but I thought it may be related. I can submit this as a new bug following the format if that's helpful.)

**Comment by kyletaylored** [comment]
> (Apologies if this is hijacking this issue, but I thought it may be related. I can submit this as a new bug following the format if that's helpful.)

Not at all, this is exactly the issue. In this case, the regex is looking for a CSS file that contains the word Bootstrap, then is preceded with a multi-digit number of some kind. (https://regexr.com/5m4pn)

```
"<link[^>]* href=[^>]*?bootstrap(?:[^>]*?([0-9a-fA-F]{7,40}|[\\d]+(?:.[\\d]+(?:.[\\d]+)?)?)|)[^>]*?(?:\\.min)?\\.css\\;version:\\1"
```

It might be best to isolate CDN provided Bootstrap libraries to reduce any errors like this (BootstrapCDN, cdnjs, jsdelivery, etc), but would also be open to other suggestions.

**Comment by danbrady** [comment]
That sounds like a good approach to me. An alternative could be: set the regex to ignore http/https protocol (if there, because that can be optional) and domain name up until the first '/', then check for matches in the rest of the file path. In other words, ignore any part of the URL that's between "//" and the first "/". That might complicate the regex a bit more, but it would get around specifying CDNs domain names.
