### ISSUE TITLE
technologies.json 中的正则表达式 ” [^] “ 是否有错误

### ISSUE THREAD

**Issue by tanjelly** [AliasIO/wappalyzer#3548]
使用 `Java`、`Python` 解析 `Wappalyzer` 的指纹库的时候发现部分正则表达式中包含 `[^]` 这种正则语法，在编译正则表达式的时候会报错，但在 `Javascript` 下执行又不会出错。请问相关指纹是否编写错误？

包含此表达式的指纹有：
- Symfony
- Liveinternet
- RDoc

**Comment by kyletaylored** [comment]
Since Wappalyzer is Javascript-based, there could be a compatibility issue when parsing between Python/Java and Javascript regex, but I do believe these existing detections could be improved.

For example, the Liveinternet detection seems overly complex and could be reduced to just a script name detection. The others we would have to figure out at well, but we could start a PR to get those changes in place and tested.
