### ISSUE TITLE
Vue.js is being shown in the list of JavaScript Frameworks for every website

### ISSUE THREAD

**Issue by Anam0927** [AliasIO/wappalyzer#3571]
**Platform**
* WebExtension (Google Chrome)

**Description**
Vue.js is being shown as one of the technologies used for every website I have visited for a while now...

**To Reproduce**
Go to any website and open the Wappalyzer extension and you'll see Vue.js as one of the technologies being used.

**Additional context**
I've seen this with a lot of websites now, and even checked with some random ones before making an issue on GitHub.

**Comment by AliasIO** [comment]
You may have another extension installed that injects Vue.js into websites. See #3444.

**Comment by Anam0927** [comment]
Thanks...

**Comment by alexanderjanke** [comment]
There seems to be another issue somewhere because I have been getting the same behaviour for a while now. Tried the obligatory reinstall of wappalyzer but no change.
You mentioned there might be some other extension running so I disabled all of the other ones:
![image](https://user-images.githubusercontent.com/33967771/101640876-5a6f8a80-3a31-11eb-88be-c5868006847e.png)

For example if I visit https://reactjs.org/ I get the following result from wappalyzer
![image](https://user-images.githubusercontent.com/33967771/101640779-37dd7180-3a31-11eb-92eb-7486d2434bde.png)

As you can see only wappalyzer is active but it still recognizes Vue... odd.

**Comment by nurbek91** [comment]
@alexanderjanke Hello my friend . Just checking in Ubuntu, Chrome 
![image](https://user-images.githubusercontent.com/3456008/101648368-f1553a80-3a63-11eb-9cd8-4d6233c62e21.png)
Shows me correctly

**Comment by alexanderjanke** [comment]
@nurbek91 you're right.. I setup an Ubuntu VM and it worked perfectly there. I also tried it on a different windows machine and it worked without issues. Now I'm stuck thinking "what is wrong with my machine?!?!" 😆 So yea, issue can stay closed I guess. My machine seems to be funky.
