### ISSUE TITLE
Wappalyzer keeps opening the Chrome JavaScript Debugger

### ISSUE THREAD

**Issue by ahmadawais** [AliasIO/wappalyzer#3684]
**Platform**
Which platform does the bug apply to?

* WebExtension (Google Chrome)

**Describe the bug**

Wappalyzer keeps opening the Chrome JavaScript Debugger

![image](https://user-images.githubusercontent.com/960133/103514340-3c5d4480-4e8e-11eb-8d2e-23b35c9aaa6c.png)

**To Reproduce**
1. Install Wappalyzer in the latest chrome
2. Go to any website and open up the chrome DevTools
3. Soon after wappalyzer debugger shows up that won't go away until I disable the extension
4. See error in the image above

**Additional context**

This started happening lately.

**Comment by kyletaylored** [comment]
I don't believe Wappalyzer would be able to enable debug settings like this arbitrarily. Did you ever start to attempt fixing any issues? Do you have developer mode enabled in Chrome? Are you using the Chrome store version or an unpacked version?

**Comment by ahmadawais** [comment]
>I don't believe Wappalyzer would be able to enable debug settings like this arbitrarily. 

I found this by enabling/disabling extensions one by one.

>Did you ever start to attempt fixing any issues? 

It happens on a couple of sites. Like here on [this site](https://osmanonline.co.uk/watch-kurulus-osman-season-2-episode-41-with-english-subtitles/) if you open the dev tools a debugging session starts.

>Do you have developer mode enabled in Chrome? 

What is that? In the chrome extensions? Yes.

>Are you using the Chrome store version or an unpacked version?

Chrome store version.

**Comment by kyletaylored** [comment]
> It happens on a couple of sites. Like here on [this site](https://osmanonline.co.uk/watch-kurulus-osman-season-2-episode-41-with-english-subtitles/) if you open the dev tools a debugging session starts.

So it happens on some sites, but not all sites? Could you provide a list of sites it happens on? I noticed that on the site you linked, it happens when I have an incognito window with no extensions and I open devtools (screenshot below), but if I have devtools open and refresh, it doesn't pause. It looks like the site includes this [Devtools Detector](https://github.com/AEPKILL/devtools-detector) script, so it leads me to believe that it's something else and not Wappalyzer related.

![image](https://user-images.githubusercontent.com/1759794/104343426-8c0cc300-54c1-11eb-9f5c-219acb186851.png)

**Comment by ahmadawais** [comment]
Ahhh must be that then. Thanks for looking into this for me.
