### ISSUE TITLE
Uptime Robot

### ISSUE THREAD

**Issue by John4266** [AliasIO/wappalyzer#3711]
Hello.
Please add UptimeRobot.

Site: https://uptimerobot.com

Example Sites:
https://status.ipapi.com
https://status.pays.host

**Comment by kyletaylored** [comment]
I didn't see anything related to a widget or service that would live on a page that could be detected. The only thing that might be detected would be a status page provided by Uptime Robot. Since it's a ping based service, I don't actually know how Wappalyzer would detect it.

Did you have an idea on how it would be detected?

**Comment by AliasIO** [comment]
It looks like we can use the status pages. It could go in the Miscellaneous category for now.
