### ISSUE TITLE
Incorrect technologies shown

### ISSUE THREAD

**Issue by hvernl** [AliasIO/wappalyzer#3769]
**Platform**
Windows
Google Chrome extension

**Describe the bug**
Wappalyzer shows wrong technologies.

**To Reproduce**
1. Go to 'https://spotler.com/'
2. Click on 'Wappalyzer extension'
3. You will see a lot of technologies but there are some that we don't use. Like Mailchimp. We don't have Mailchimp. The word 'Mailchimp' is used on a page but Wappalyzer searches for technologies and not content, right?

https://spotler.com also shows technologies used on a subdomain (https://helpcenter.spotler.com/) that are not used on the main domain (https://spotler.com/).

**Expected behavior**
Not to show technologies we don't use.

**Comment by nurbek91** [comment]
Hey mate . Just add a review
![image](https://user-images.githubusercontent.com/3456008/107802992-3b240f00-6d8c-11eb-890b-88a4fef68729.png)
Ubuntu , Chrome extension (6.5.26 version) without Mailchimp.

**Comment by endermctv** [comment]
@nurbek91 Me same. But I don't understand: PHP and Lua?

**Comment by hvernl** [comment]
@nurbek91 It was gone, but now it is showing all the technologies of subdomains again and Mailchimp for example which we don't use.

**Comment by endermctv** [comment]
@hvernl Did you trying to clear the cached detections? Ask me if you don't know how to do

**Comment by kyletaylored** [comment]
@hvernl One of the detection areas is content on the page, for example you can scan for metatags or comments that are injected by proprietary systems.

Some other things are implied by software that IS detected - for example, if using WordPress, PHP and MySQL are added because WordPress runs on those technologies. Does that make sense?

Checking right now, I actually don't see Mailchimp in the list, but I do think there is an issue with the caching right now that I'm going to look into.

**Comment by AliasIO** [comment]
Lua is being reported because OpenResty uses it. I actually changed recently it to not report Lua because it's not very useful to include it here.

I'm not seeing Mailchimp being reported, I'm not sure what might have triggered that.

Results from subdomains are not be shown on the main domain.
