### ISSUE TITLE
npm cli does not follow <meta> redirects

### ISSUE THREAD

**Issue by smokeyflavor** [AliasIO/wappalyzer#3785]
**Platform**
Which platform does the bug apply to?
* NPM

**Describe the bug**

When using the npm cli to detect apps on websites that have <meta> redirects, the browser does not follow the redirect because it's a non-standard redirect, unlike 302 in the HTTP headers.

For example if the website responds with this HTML:
```
<html>
    <head>
        <meta HTTP-EQUIV="REFRESH" content="0; url=/app/">
    </head>
</html>
```
The browser will not follow to `/app/` and thus the applications will not be detected at all

**Comment by AliasIO** [comment]
We deliberately block in-page navigation requests because it interferes with scraping. When it happens, Puppeteer would throw 'Execution context was destroyed, most likely because of a navigation'. There might be a better way to deal with this.

https://github.com/AliasIO/wappalyzer/blob/master/src/drivers/npm/driver.js#L353

**Comment by smokeyflavor** [comment]
@AliasIO The reason you've chosen puppeteer as the core engine for the scraper is because of the javascript engine right? Otherwise it would be better to just make HTTP requests

**Comment by AliasIO** [comment]
That's the main reason but there are many other browser APIs as well, like DOM, WebSockets, etc. Just using HTML results in far fewer detections.
