### ISSUE TITLE
Improve 'Smile' loyalty solution detection

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4194]
We added detection for 'Smile' in https://github.com/AliasIO/wappalyzer/issues/4122 but looks like this doesn't cover implementations on 'Wix'

Example site - https://www.coalandcanary.com/

Add additional checks by checking for https://js.smile.io/v1/smile-wix.js

Current Detection is - 

    "Smile": {
      "cats": [
        6
      ],
      "description": "Smile is a provider of ecommerce loyalty programs.",
      "icon": "Smile.svg",
      "js": {
        "Smile.channel_key": ""
      },
      "scripts": "js\\.smile\\.io/v([\\d.]+)/\\;version:\\1",
      "saas": true,
      "pricing": [
        "freemium",
        "mid",
        "recurring"
      ],
      "website": "https://smile.io"
    }

**Comment by nurbek91** [comment]
Hey mate 
![image](https://user-images.githubusercontent.com/3456008/126336907-a2c983eb-48c9-4b85-9884-2fbb9cb441fa.png)
The current version defines the technology.
Rather, this is due to the fact that these files do not have time to load when the extension has already finished working. 
Same as #4192 , #4193

**Comment by nurbek91** [comment]
@rockeynebhwani  Nevermind , just update  Chrome extension to  6.7.10 its also solve #4192 , #4193 issues
![image](https://user-images.githubusercontent.com/3456008/126337994-f84aadcd-0ce2-40a1-b27a-3062e9823867.png)

**Comment by rockeynebhwani** [comment]
Thanks @nurbek91 . We can close this.
