### ISSUE TITLE
Update 'Yahoo Advertising'

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4394]
Yahoo advertising is now Verizon advertising

Current detection - 

```
    "Yahoo Advertising": {
      "cats": [
        36
      ],
      "html": [
        "<iframe[^>]+adserver\\.yahoo\\.com",
        "<img[^>]+clicks\\.beap\\.bc\\.yahoo\\.com"
      ],
      "icon": "yahoo.png",
      "js": {
        "adxinserthtml": ""
      },
      "scripts": "adinterax\\.com",
      "website": "http://advertising.yahoo.com"
    },
```

Keep old detection methods and make following changes - 
- Update website to https://www.verizonmedia.com/advertising
- check for JS object 'dotq'
- check for script https://s.yimg.com/wi/ytc.js
- Update Yahoo logo to Verizon Media logo
-  Change the name from 'Yahoo Advertising' to 'Verizon Media'

**Comment by nurbek91** [comment]
Hey @rockeynebhwani need your hints
1)We have other technologies that start at Yahoo
![image](https://user-images.githubusercontent.com/3456008/140655817-7e23c08b-0d78-4c62-8101-bb45dc43421b.png)
Should we reimplement other technologies in Verizon.
2) We also have the already added  Verizon Media.
https://www.wappalyzer.com/technologies/advertising/verizon-media/
3 ) Yahoo Advertising probably need to be deleted since it does not have
https://www.wappalyzer.com/technologies/advertising/yahoo-advertising/
4) ` https://s.yimg.com/wi/ytc.js` it is necessary that this particular script is completely carried out fo Verizon Media or `yimg.com/` ok

**Comment by rockeynebhwani** [comment]
@nurbek91 - Since I raised this issue, I realise that Verizon has sold Yahoo and Yahoo again is going to be an independent brand - https://www.capacitymedia.com/articles/3829495/yahoo-due-back-today-after-five-year-gap-as-verizon-sells-for-5bn

**Comment by nurbek91** [comment]
Hey @AliasIO , might have to close.
