### ISSUE TITLE
Track 'Google Core Web Vitals' Library

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4423]
Vendor Site - https://github.com/GoogleChrome/web-vitals
Example Site - https://www.rimowa.com/gb/en/home (Select country UK)
Category - 78 (RUM) / 59 (JavaScript libraries)
Detection - Check for script https://unpkg.com/web-vitals@2.0.1/dist/web-vitals.umd.js (where 2.0.1 is the version)

**Comment by AliasIO** [comment]
I see we're finally going full circle. :)

**Comment by rviscomi** [comment]
cc @philipwalton

**Comment by AliasIO** [comment]
Right, we only inspect the main frame. I would like to have a solution for bundled code but I want to avoid scanning potentially many and large assets per page.

**Comment by philipwalton** [comment]
@AliasIO in case it's helpful, I checked the data for this detection against the September HTTP Archive data to compare results detected by Wappalyzer vs. the [built-in `getWebVitalsJS()` detection](https://github.com/HTTPArchive/legacy.httparchive.org/pull/224) added to HTTP Archive that checks the contents of response bodies.

For the `web-vitals` library, Wappalyzer is off by **almost 10x**.

Here are the queries I used:

```sql
SELECT COUNT(DISTINCT url) as Count
FROM `httparchive.technologies.2021_09_01_*`
WHERE app = 'Google Core Web Vitals'
```

This query (which uses Wappalyzer) returns:

| Row | Count |
| --- | --- |
| 1 | 58456 |

```sql
SELECT COUNT(DISTINCT url) AS Count
FROM
  `httparchive.pages.2021_09_01_*`,
  UNNEST(JSON_VALUE_ARRAY(payload, '$._performance.web_vitals_js'))
```

This query (which uses the built-in `getWebVitalsJS()`) function returns:

| Row | Count |
| --- | --- |
| 1 | 553032 |

This is a pretty big difference, but it doesn't surprise me since I know most people who use the `web-vitals` JS library don't load it from a CDN, they bundle it with their application code.

I'm not sure if the `web-vitals` library is a special case or if other JS libraries should expect to be off by a similar amounts. But given that most JS libraries these days are moving away from browser globals and toward modules, I think this problem is only going to get bigger in the future.

(cc: @rviscomi @housseindjirdeh)

**Comment by AliasIO** [comment]
Yes, of course. The library is called `web-vitals` so that would be a sensible choice.
