### ISSUE TITLE
Issue with 'WooCommerce' detection in Sep-2021 HTTPArchive Crawl

### ISSUE THREAD

**Issue by rockeynebhwani** [AliasIO/wappalyzer#4843]
@nurbek91  / @AliasIO - Can we please check if anything changed with respect to detection of 'WooCommerce'. In Sep-2021 HTTP Archive crawl, we are seeing a big drop in WooCommerce based origins

https://datastudio.google.com/s/jWtax6ONe9Q

![image](https://user-images.githubusercontent.com/1718757/137103152-6c60c42e-6da8-4896-a7fa-777274662526.png)

@rviscomi  - FYI

**Comment by pmeenan** [comment]
Only way to prevent unexpected changes from month to month would be to not update the Wappalyzer detection engine and rules on the WebPageTest side. But then you also won't get any improvements to the rules or new detections.

Beyond that, you could have a representative set of URLs that capture all of the platforms you want to make sure are always caught and monitor them on a regular basis outside of HA (maybe as a test suite before committing a WPT change). That will be fragile to site changes though.

**Comment by pmeenan** [comment]
Whatever this is doing in Wappalyzer.SetTechnologies():
```js
      Wappalyzer.technologies = Wappalyzer.technologies.filter(
        ({ requires }) => !requires.length
      )
```

Right at the end of setting the technologies is deleting the definition for Woocommerce (so it never gets run, along with a few others).

**Comment by pmeenan** [comment]
Verified that if I comment out that filter at the end of setTechnologies, the WooCommerce technology remains in place (as well as a few dozen others) and correctly gets detected.  @AliasIO do you happen to know what it is there for and why it isn't tripping up the hosted version?

All WPT is doing to reproduce is loading all of the individual technologies file into a giant dictionary and then passing it to setTechnologies(). After that WooCommerce is gone.  As best as I can tell, that's what the sample code does too.

Maybe because we're using ToT and not a branch?

**Comment by AliasIO** [comment]
@pmeenan The `requires` field was [added](https://github.com/AliasIO/wappalyzer/issues/4007#issuecomment-866471584) to conditionally check for technologies when a dependency is found, e.g. we only look for WooCommerce if WordPress is detected first.

As a workaround, you can replace all occurrences of `requires` with `implies` in the technology files before passing it to `Wappalyzer.setTechnologies()`.

[Above](https://github.com/AliasIO/wappalyzer/blob/master/src/wappalyzer.js#L354) the line you found, we store technologies with a `requires` field in a separate object:

```javascript
Wappalyzer.requires = Object.keys(Wappalyzer.requires).map((name) => ({
  name,
  technologies: Wappalyzer.requires[name],
}))

Wappalyzer.technologies = Wappalyzer.technologies.filter(
  ({ requires }) => !requires.length
 )
```

Then when we identify a technology, we check if any other technologies 'require' it and run a separate analysis:

https://github.com/AliasIO/wappalyzer/blob/master/src/drivers/npm/driver.js#L1111

We're about to add a few hundred WordPress themes and plugins. The `requires` field was added so we only look for those when WordPress is present.

**Comment by AliasIO** [comment]
Ideally `Wappalyzer` can just call `Driver.querySelector()` and the logic stays in core. The WebExtension driver works by having a content script inject a script into the page in order to access node properties, whereas the NPM driver calls Puppeteer's `page.evaluate()`. Right now this happens in a single pass, doing this for every call to `querySelector` wouldn't work well. The APIs are very different between drivers.

**Comment by rockeynebhwani** [comment]
@AliasIO  @pmeenan @rviscomi -  I see WooCommerce counts improving in Oct crawl. Let's wait for Nov crawl results as I think full recovery will be seen only as part of Nov crawl

**Comment by rockeynebhwani** [comment]
@AliasIO @pmeenan @rviscomi  - We have seen fully recovery in WooCommerce stats in Nov crawl. We can close this. Thanks..
