### ISSUE TITLE
Magento and PHP on Google services (50% sure)

### ISSUE THREAD

**Issue by synth3tk** [AliasIO/Wappalyzer#703]
I'm no expert in Google's technology, but that definitely sounds wrong to me.

**Comment by mydnic** [comment]
"Magento (50% sure)" also appears on Google Inbox (inbox.google.com)

**Comment by kolen** [comment]
Most likely, ``Mage`` appears in global variables, global variables with short random names are common to Google webpages.

``"env": "^(?:Mage|VarienForm)$",``

**Comment by q--** [comment]
The Google Closure compiler generates JavaScript with all variable names replaced by sequences of chacaracters that are are as short as possible. If there are lots of variables, it will start generating 4-character names.

Because this doesn't occur frequently (though it occurs at some high-profile web sites), a certainty of 50% for this rule seems okay to me.

Perhaps hard-coded exceptions for certain web sites could be built into the extension, but I'm not sure it's worth it.

**Comment by AliasIO** [comment]
Forcing case sensitivity might help here. Every regex is case insensitive by default, perhaps we can add a flag to negate this, e.g. `"env": "^Mage$\\;c"`. Or perhaps `env` should always be case senstive.

**Comment by q--** [comment]
I don't think that will help here, as Closure Compiler generates variable names with A-Z, a-z and $.

**Comment by AliasIO** [comment]
Sure, but instead of matching 4^2 = 16 possible combinations in this case it will only match one.
