### ISSUE TITLE
Use of Cowboy server software is misleadingly suggesting that apps are using Erlang

### ISSUE THREAD

**Issue by KelseyDH** [AliasIO/Wappalyzer#849]
I have multiple Rails apps on Heroku that do not use Erlang.  Recently I noticed that Wappalyzer has been flagging them as Erlang in addition Rails due to (presumably) Heroku using Cowboy internally to handle all of its hosted servers for clients.

These Rails apps on Heroku never made any design decisions at all towards Cowboy or Erlang, so labeling them as Erlang is highly misleading, and will probably screw up stats about language design choices that Wappalyzer is trying to collect.

**Comment by dgmstuart** [comment]
+1

My Rails app (https://github.com/dgmstuart/Swing-Out-London) is getting flagged as Cowboy/Erlang on the admin pages - hosted on heroku

**Comment by KelseyDH** [comment]
@dgmstuart For reasons unknown to me (perhaps Heroku changed their servers?), Wappalyzer is no longer detecting Cowboy with my rails app.  Can you confirm it's changed for you too?

**Comment by dgmstuart** [comment]
Nope - still showing cowboy for me. There was an update to the plugin recently, but that doesn't seem to have changed its behaviour.

My apps all say "rails - 50% sure" though...

**Comment by toastal** [comment]
As a Rails guy, you've probably heard of Elixir and Chris McCord and José Valim's [Phoenix framework](http://www.phoenixframework.org/) at least. That framework is built on one of Erlang's most popular web frameworks, Cowboy, which is Heroku maintains its own fork of for its proxy. You can see Wappalyzer working correctly at [PhoenixCasts](http://phoenixscreencasts.com/). Unless you can distinguish the Heroku from the non-Heroku, it's working as intended. It's in the same vein as most websites showing Apache or Nginx because that's the reverse proxy server. The headers show Cowboy, so it's Cowboy bygolly.

**Comment by AliasIO** [comment]
Although it's working as intended I agree it's a little misleading. We don't report C when a website is running on Linux.

**Comment by toastal** [comment]
Same could be said for C and Nginx, et. al. The tricky one with this is that Cowboy IS one of the most popular Erlang/Elixir frameworks and I know people writing apps in those languages... it just happens that a disproportionate amount of the requests that hit that framework are from Heroku's proxy fork because of it's SaaS prevalence. Is there a way to add up headers to get a better idea--like no `Vegur` (I think)?

**Comment by dgmstuart** [comment]
@toastal I guess the thing is that we're expecting that the thing at the top of the list (/shown in the address bar) should be the main _application_ technology: certainly that's the most interesting bit of information for me. 

However I can see that this is maybe an unrealistic expectation - particularly in a case like this where there are multiple technologies used which can be used as application frameworks. 

I wonder if it would make sense to add specific precedence rules for the case of multiple app frameworks? e.g:

* If Cowboy, Rails and Angular are detected, this is probably thought of as a Rails app, since I assume it's unlikely that a Cowboy app would be running Rails as part of its stack.
* If Angular and Bootstrap are detected, this is probably thought of as an Angular app - but I've seen a number of apps like this (or using e.g. Backbone) which show up as Bootstrap in the address bar.

Of course this gets ambiguous - e.g. in an ember/rails app it might be a matter of opinion about which is the primary technology.

Anyway I guess the benefit is marginal as long as all the technologies are shown in the list.

**Comment by AliasIO** [comment]
We could perhaps visually distinguish between detected and implied applications.
